github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

image:
  file: .gitpod.Dockerfile

#
#tasks:
#- before: export ROOT_URL=$(gp url 3000)
#  init: meteor npm install
##  command: meteor
#ports:
#- port: 3000
#  onOpen: open-preview
#- port: 3001 # mongo db
#  onOpen: ignore


# And install meteor.
# curl https://install.meteor.com/ | sh

# There will be warning messages,  you do not have and do not need sudo (root access) on Gitpod.    Next, add the newly installed meteor to your path.
# PATH=$PATH:/home/gitpod/.meteor

# Finally,  install the node dependencies and start your server.
# meteor npm i
# meteor npm start
